"""update department

Revision ID: 1cd2711714d9
Revises: 504679f9b55e
Create Date: 2025-07-11 10:52:29.804181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd2711714d9'
down_revision = '504679f9b55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_manager_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('second_manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['second_manager_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['first_manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('second_manager_id')
        batch_op.drop_column('first_manager_id')

    # ### end Alembic commands ###
