"""update department and user columns

Revision ID: 4e640ae1711b
Revises: 7260dcfb0753
Create Date: 2025-07-04 10:45:49.534092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e640ae1711b'
down_revision = '7260dcfb0753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('dpid', sa.Integer(), nullable=False),
    sa.Column('dpname', sa.String(length=20), nullable=False),
    sa.Column('father_db', sa.Integer(), nullable=True),
    sa.Column('child_db', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Enum('Y', 'N'), nullable=True),
    sa.Column('creat_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('dpid'),
    sa.UniqueConstraint('dpname')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['dpid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')

    op.drop_table('departments')
    # ### end Alembic commands ###
