"""update department

Revision ID: 504679f9b55e
Revises: e9267ad569fb
Create Date: 2025-07-11 09:58:10.259797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '504679f9b55e'
down_revision = 'e9267ad569fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
