"""init users

Revision ID: 5589cca21f9b
Revises: 
Create Date: 2025-07-03 11:06:49.865644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5589cca21f9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=10), nullable=False),
    sa.Column('role', sa.Enum('doctor', 'admin', 'staff'), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('declare_name', sa.String(length=10), nullable=True),
    sa.Column('declare_id', sa.String(length=10), nullable=True),
    sa.Column('practice_start', sa.Date(), nullable=True),
    sa.Column('practice_end', sa.Date(), nullable=True),
    sa.Column('onboard', sa.DateTime(), nullable=True),
    sa.Column('resignation_day', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('role', mysql.ENUM('doctor', 'admin', 'staff'), nullable=True),
    sa.Column('create_at', mysql.DATETIME(), nullable=True),
    sa.Column('declare_name', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('declare_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('practice_start', sa.DATE(), nullable=True),
    sa.Column('practice_end', sa.DATE(), nullable=True),
    sa.Column('onboard', mysql.DATETIME(), nullable=True),
    sa.Column('resignation_day', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('users')
    # ### end Alembic commands ###
