"""add organization_id to departments

Revision ID: 705dc3e63c70
Revises: f263a8b0755d
Create Date: 2025-07-10 14:54:01.490446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '705dc3e63c70'
down_revision = 'f263a8b0755d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.alter_column('father_db',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('cost',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=False)
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cost',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=True)
        batch_op.alter_column('father_db',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
