"""add organization_id to departments

Revision ID: e9267ad569fb
Revises: 705dc3e63c70
Create Date: 2025-07-10 15:40:38.303710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9267ad569fb'
down_revision = '705dc3e63c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('father_db',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('father_db',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
