"""add organization table

Revision ID: f263a8b0755d
Revises: 4e640ae1711b
Create Date: 2025-07-10 11:36:48.563418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f263a8b0755d'
down_revision = '4e640ae1711b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orgname', sa.String(length=20), nullable=False),
    sa.Column('father_org', sa.Integer(), nullable=True),
    sa.Column('level', sa.Enum('Operations Center', 'Campus', 'Branch'), nullable=False),
    sa.Column('creat_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orgname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizations')
    # ### end Alembic commands ###
